#ifndef FLEX_HEADER_dmanScanner_h
#define FLEX_HEADER_dmanScanner_h
#define YY_DmanScanner_CHAR unsigned char
#line 1 "/u/icdc/rdt/tools/lib/flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#include <stdio.h>




/* % here is the declaration from section1 %header{  */ 
#line 28 "dmanScanner.l"
#define YY_DmanScanner_INHERIT 
#line 29 "dmanScanner.l"
#define YY_DmanScanner_LEX_RETURN  int
#line 30 "dmanScanner.l"
#define YY_DmanScanner_LEX  ScanValue
#line 31 "dmanScanner.l"
#define YY_DmanScanner_LEX_PARAM  TokenValue &theValue
#line 32 "dmanScanner.l"
#define YY_DmanScanner_MEMBERS   \
	protected: \
	int theLine,theColumn; \
	void BeginAction(); \
	virtual void SetDebug(int)=0;
#line 37 "dmanScanner.l"
#define YY_DmanScanner_CONSTRUCTOR_PARAM  void
#line 38 "dmanScanner.l"
#define YY_DmanScanner_CONSTRUCTOR_INIT  : theLine(1),theColumn(1)
#line 39 "dmanScanner.l"
#define YY_DmanScanner_CONSTRUCTOR_CODE  ;
#line 40 "dmanScanner.l"
#define YY_DmanScanner_TEXT  theText
#line 41 "dmanScanner.l"
#define YY_DmanScanner_LENG  theTextLength
#line 52 "dmanScanner.l"
#line 52 "/u/icdc/rdt/tools/lib/flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_DmanScanner_IOSTREAM
#include <iostream.h>
#define YY_DmanScanner_IFILE  istream
#define YY_DmanScanner_OFILE ostream 
#define YY_DmanScanner_ERRFILE cerr

#ifndef YY_DmanScanner_IFILE_DEFAULT
#define YY_DmanScanner_IFILE_DEFAULT &cin
#endif

#ifndef YY_DmanScanner_OFILE_DEFAULT
#define YY_DmanScanner_OFILE_DEFAULT &cout
#endif

#endif
#endif

#ifndef YY_DmanScanner_IFILE
#define YY_DmanScanner_IFILE FILE 
#endif

#ifndef YY_DmanScanner_OFILE
#define YY_DmanScanner_OFILE FILE 
#endif

#ifndef YY_DmanScanner_ERRFILE
#define YY_DmanScanner_ERRFILE stderr
#endif

#ifndef YY_DmanScanner_IFILE_DEFAULT
#define YY_DmanScanner_IFILE_DEFAULT stdin
#endif

#ifndef YY_DmanScanner_OFILE_DEFAULT
#define YY_DmanScanner_OFILE_DEFAULT stdout
#endif




#ifndef YY_DmanScanner_TEXT
#define YY_DmanScanner_TEXT yytext
#endif
#ifndef YY_DmanScanner_LENG
#define YY_DmanScanner_LENG yyleng
#endif
#ifndef YY_DmanScanner_IN
#define YY_DmanScanner_IN yyin
#endif
#ifndef YY_DmanScanner_OUT
#define YY_DmanScanner_OUT yyout
#endif

#ifndef YY_DmanScanner_LEX_RETURN
#define YY_DmanScanner_LEX_RETURN int
#else
#ifndef YY_DmanScanner_LEX_DEFINED
#define YY_DmanScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_DmanScanner_LEX
#define YY_DmanScanner_LEX yylex
#else
#ifndef YY_DmanScanner_LEX_DEFINED
#define YY_DmanScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_DmanScanner_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_DmanScanner_LEX_PARAM 
#else
#define YY_DmanScanner_LEX_PARAM void
#endif
#else
#ifndef YY_DmanScanner_LEX_DEFINED
#define YY_DmanScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_DmanScanner_LEX_PARAM_DEF
#define YY_DmanScanner_LEX_PARAM_DEF
#else
#ifndef YY_DmanScanner_LEX_DEFINED
#define YY_DmanScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_DmanScanner_RESTART
#define YY_DmanScanner_RESTART yyrestart
#endif
#ifndef YY_DmanScanner_SWITCH_TO_BUFFER
#define YY_DmanScanner_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_DmanScanner_LOAD_BUFFER_STATE
#define YY_DmanScanner_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_DmanScanner_CREATE_BUFFER
#define YY_DmanScanner_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_DmanScanner_DELETE_BUFFER
#define YY_DmanScanner_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_DmanScanner_INIT_BUFFER
#define YY_DmanScanner_INIT_BUFFER yy_init_buffer
#endif
#ifdef YY_DmanScanner_FLEX_DEBUG
#ifndef YY_DmanScanner_DEBUG
#define YY_DmanScanner_DEBUG 1
#endif
#else
#ifndef YY_DmanScanner_DEBUG
#define YY_DmanScanner_DEBUG 0
#endif
#endif

#if YY_DmanScanner_DEBUG != 0
#ifndef YY_DmanScanner_DEBUG_FLAG
#define YY_DmanScanner_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_DmanScanner_DEBUG_INIT
#define YY_DmanScanner_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_DmanScanner_RESTART YY_PROTO(( YY_DmanScanner_IFILE *input_file ));
extern void YY_DmanScanner_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_DmanScanner_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_DmanScanner_CREATE_BUFFER YY_PROTO(( YY_DmanScanner_IFILE *file, int size ));
extern void YY_DmanScanner_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_DmanScanner_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_DmanScanner_IFILE *file ));

#if YY_DmanScanner_DEBUG != 0
extern int YY_DmanScanner_DEBUG_FLAG ;
#endif
extern YY_DmanScanner_CHAR  *YY_DmanScanner_TEXT;
extern int YY_DmanScanner_LENG;
extern YY_DmanScanner_IFILE *YY_DmanScanner_IN, *YY_DmanScanner_OUT;
#ifdef YY_DmanScanner_LEX_DEFINED
extern YY_DmanScanner_LEX_RETURN YY_DmanScanner_LEX ( YY_DmanScanner_LEX_PARAM )
YY_DmanScanner_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_DmanScanner_LEX_RETURN YY_DmanScanner_LEX ( YY_DmanScanner_LEX_PARAM )
YY_DmanScanner_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_DmanScanner_CLASS
#define YY_DmanScanner_CLASS DmanScanner
#endif
#ifndef YY_DmanScanner_ECHO
#define YY_DmanScanner_ECHO yy_echo
#endif
#ifdef YY_DmanScanner_ECHO_PURE
#define YY_DmanScanner_ECHO_NOCODE
#endif

#ifndef YY_DmanScanner_ECHO_CODE
#ifndef YY_DmanScanner_IOSTREAM
#define YY_DmanScanner_ECHO_CODE fwrite( (char *) YY_DmanScanner_TEXT, YY_DmanScanner_LENG, 1, YY_DmanScanner_OUT );
#else
#define YY_DmanScanner_ECHO_CODE (YY_DmanScanner_OUT->write( (char *) YY_DmanScanner_TEXT, YY_DmanScanner_LENG));
#endif
#endif

#ifndef YY_DmanScanner_INPUT
#define YY_DmanScanner_INPUT yy_input
#endif
#ifdef YY_DmanScanner_INPUT_PURE
#define YY_DmanScanner_INPUT_NOCODE
#endif

#ifndef YY_DmanScanner_INPUT_CODE
#ifndef YY_DmanScanner_IOSTREAM
#define YY_DmanScanner_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_DmanScanner_IN );
#else
#define YY_DmanScanner_INPUT_CODE if(YY_DmanScanner_IN->eof())  result=0;else {YY_DmanScanner_IN->read(buffer,max_size);YY_DmanScanner_IN->result=YY_DmanScanner_IN->gcount();YY_DmanScanner_IN->clear(YY_DmanScanner_IN->rdstate()&(~ios::failbit));if(YY_DmanScanner_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_DmanScanner_FATAL_ERROR_PURE
#define YY_DmanScanner_FATAL_ERRO_NOCODE
#endif
#ifndef YY_DmanScanner_FATAL_ERROR
#define YY_DmanScanner_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_DmanScanner_FATAL_ERROR_CODE
#ifndef YY_DmanScanner_IOSTREAM
#define YY_DmanScanner_FATAL_ERROR_CODE fputs( msg, YY_DmanScanner_ERRFILE );putc( '\n', YY_DmanScanner_ERRFILE );exit( 1 );
#else
#define YY_DmanScanner_FATAL_ERROR_CODE YY_DmanScanner_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_DmanScanner_WRAP
#define YY_DmanScanner_WRAP yy_wrap
#endif
#ifdef YY_DmanScanner_WRAP_PURE
#define YY_DmanScanner_WRAP_NOCODE
#endif
#ifndef YY_DmanScanner_WRAP_CODE
#define YY_DmanScanner_WRAP_CODE return 1;
#endif


#ifndef YY_DmanScanner_INHERIT
#define YY_DmanScanner_INHERIT
#endif
#ifndef YY_DmanScanner_MEMBERS
#define YY_DmanScanner_MEMBERS 
#endif
#ifndef YY_DmanScanner_CONSTRUCTOR_PARAM
#define YY_DmanScanner_CONSTRUCTOR_PARAM
#endif
#ifndef YY_DmanScanner_CONSTRUCTOR_CODE
#define YY_DmanScanner_CONSTRUCTOR_CODE
#endif
#ifndef YY_DmanScanner_CONSTRUCTOR_INIT
#define YY_DmanScanner_CONSTRUCTOR_INIT
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_DmanScanner_CLASS YY_DmanScanner_INHERIT
{
 private:/* data */
 YY_DmanScanner_CHAR  *yy_c_buf_p;
 YY_DmanScanner_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_DmanScanner_CHAR  c, YY_DmanScanner_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE yy_current_buffer;
 void YY_DmanScanner_RESTART ( YY_DmanScanner_IFILE *input_file );
 void YY_DmanScanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_DmanScanner_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_DmanScanner_CREATE_BUFFER( YY_DmanScanner_IFILE *file, int size );
 void YY_DmanScanner_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_DmanScanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_DmanScanner_IFILE *file );
 protected: /* virtual */
 virtual void YY_DmanScanner_ECHO()
#ifdef YY_DmanScanner_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_DmanScanner_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_DmanScanner_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_DmanScanner_FATAL_ERROR(char *msg)
#ifdef YY_DmanScanner_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_DmanScanner_WRAP()
#ifdef YY_DmanScanner_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_DmanScanner_CHAR  *YY_DmanScanner_TEXT;
 int YY_DmanScanner_LENG;
 YY_DmanScanner_IFILE *YY_DmanScanner_IN, *YY_DmanScanner_OUT;
 YY_DmanScanner_LEX_RETURN YY_DmanScanner_LEX ( YY_DmanScanner_LEX_PARAM);
 YY_DmanScanner_CLASS(YY_DmanScanner_CONSTRUCTOR_PARAM) ;
#if YY_DmanScanner_DEBUG != 0
 int YY_DmanScanner_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_DmanScanner_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 156 "dmanScanner.l"
#endif
#line 360 "/u/icdc/rdt/tools/lib/flexskel.h"

/* end of generated header */
