#ifndef FLEX_HEADER_MyScannerIOS_h
#define FLEX_HEADER_MyScannerIOS_h
#define YY_MyScanner_CHAR unsigned char
#line 1 "/u/icdc/rdt/tools/lib/flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#include <stdio.h>




/* % here is the declaration from section1 %header{  */ 
#line 19 "MyScannerIOS.l"
#define YY_MyScanner_IOSTREAM 
#line 20 "MyScannerIOS.l"
#define YY_MyScanner_LEX_PARAM  YY_MyParser_STYPE *val,YY_MyParser_LTYPE *loc
#line 21 "MyScannerIOS.l"
#define YY_MyScanner_MEMBERS  public: int theLine,theColumn;
#line 22 "MyScannerIOS.l"
#define YY_MyScanner_CONSTRUCTOR_INIT  : theLine(1),theColumn(1)
#line 24 "MyScannerIOS.l"
#include "MyParserIOS.h"
#line 33 "MyScannerIOS.l"
#line 52 "/u/icdc/rdt/tools/lib/flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_MyScanner_IOSTREAM
#include <iostream.h>
#define YY_MyScanner_IFILE  istream
#define YY_MyScanner_OFILE ostream 
#define YY_MyScanner_ERRFILE cerr

#ifndef YY_MyScanner_IFILE_DEFAULT
#define YY_MyScanner_IFILE_DEFAULT &cin
#endif

#ifndef YY_MyScanner_OFILE_DEFAULT
#define YY_MyScanner_OFILE_DEFAULT &cout
#endif

#endif
#endif

#ifndef YY_MyScanner_IFILE
#define YY_MyScanner_IFILE FILE 
#endif

#ifndef YY_MyScanner_OFILE
#define YY_MyScanner_OFILE FILE 
#endif

#ifndef YY_MyScanner_ERRFILE
#define YY_MyScanner_ERRFILE stderr
#endif

#ifndef YY_MyScanner_IFILE_DEFAULT
#define YY_MyScanner_IFILE_DEFAULT stdin
#endif

#ifndef YY_MyScanner_OFILE_DEFAULT
#define YY_MyScanner_OFILE_DEFAULT stdout
#endif




#ifndef YY_MyScanner_TEXT
#define YY_MyScanner_TEXT yytext
#endif
#ifndef YY_MyScanner_LENG
#define YY_MyScanner_LENG yyleng
#endif
#ifndef YY_MyScanner_IN
#define YY_MyScanner_IN yyin
#endif
#ifndef YY_MyScanner_OUT
#define YY_MyScanner_OUT yyout
#endif

#ifndef YY_MyScanner_LEX_RETURN
#define YY_MyScanner_LEX_RETURN int
#else
#ifndef YY_MyScanner_LEX_DEFINED
#define YY_MyScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_MyScanner_LEX
#define YY_MyScanner_LEX yylex
#else
#ifndef YY_MyScanner_LEX_DEFINED
#define YY_MyScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_MyScanner_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_MyScanner_LEX_PARAM 
#else
#define YY_MyScanner_LEX_PARAM void
#endif
#else
#ifndef YY_MyScanner_LEX_DEFINED
#define YY_MyScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_MyScanner_LEX_PARAM_DEF
#define YY_MyScanner_LEX_PARAM_DEF
#else
#ifndef YY_MyScanner_LEX_DEFINED
#define YY_MyScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_MyScanner_RESTART
#define YY_MyScanner_RESTART yyrestart
#endif
#ifndef YY_MyScanner_SWITCH_TO_BUFFER
#define YY_MyScanner_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_MyScanner_LOAD_BUFFER_STATE
#define YY_MyScanner_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_MyScanner_CREATE_BUFFER
#define YY_MyScanner_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_MyScanner_DELETE_BUFFER
#define YY_MyScanner_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_MyScanner_INIT_BUFFER
#define YY_MyScanner_INIT_BUFFER yy_init_buffer
#endif
#ifdef YY_MyScanner_FLEX_DEBUG
#ifndef YY_MyScanner_DEBUG
#define YY_MyScanner_DEBUG 1
#endif
#else
#ifndef YY_MyScanner_DEBUG
#define YY_MyScanner_DEBUG 0
#endif
#endif

#if YY_MyScanner_DEBUG != 0
#ifndef YY_MyScanner_DEBUG_FLAG
#define YY_MyScanner_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_MyScanner_DEBUG_INIT
#define YY_MyScanner_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_MyScanner_RESTART YY_PROTO(( YY_MyScanner_IFILE *input_file ));
extern void YY_MyScanner_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_MyScanner_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_MyScanner_CREATE_BUFFER YY_PROTO(( YY_MyScanner_IFILE *file, int size ));
extern void YY_MyScanner_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_MyScanner_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_MyScanner_IFILE *file ));

#if YY_MyScanner_DEBUG != 0
extern int YY_MyScanner_DEBUG_FLAG ;
#endif
extern YY_MyScanner_CHAR  *YY_MyScanner_TEXT;
extern int YY_MyScanner_LENG;
extern YY_MyScanner_IFILE *YY_MyScanner_IN;
extern YY_MyScanner_OFILE *YY_MyScanner_OUT;
#ifdef YY_MyScanner_LEX_DEFINED
extern YY_MyScanner_LEX_RETURN YY_MyScanner_LEX ( YY_MyScanner_LEX_PARAM )
YY_MyScanner_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_MyScanner_LEX_RETURN YY_MyScanner_LEX ( YY_MyScanner_LEX_PARAM )
YY_MyScanner_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_MyScanner_CLASS
#define YY_MyScanner_CLASS MyScanner
#endif
#ifndef YY_MyScanner_ECHO
#define YY_MyScanner_ECHO yy_echo
#endif
#ifdef YY_MyScanner_ECHO_PURE
#define YY_MyScanner_ECHO_NOCODE
#endif

#ifndef YY_MyScanner_ECHO_CODE
#ifndef YY_MyScanner_IOSTREAM
#define YY_MyScanner_ECHO_CODE fwrite( (char *) YY_MyScanner_TEXT, YY_MyScanner_LENG, 1, YY_MyScanner_OUT );
#else
#define YY_MyScanner_ECHO_CODE (YY_MyScanner_OUT->write( (char *) YY_MyScanner_TEXT, YY_MyScanner_LENG));
#endif
#endif

#ifndef YY_MyScanner_INPUT
#define YY_MyScanner_INPUT yy_input
#endif
#ifdef YY_MyScanner_INPUT_PURE
#define YY_MyScanner_INPUT_NOCODE
#endif

#ifndef YY_MyScanner_INPUT_CODE
#ifndef YY_MyScanner_IOSTREAM
#define YY_MyScanner_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_MyScanner_IN );
#else
#define YY_MyScanner_INPUT_CODE if(YY_MyScanner_IN->eof())  result=0;else {YY_MyScanner_IN->read(buffer,max_size);result=YY_MyScanner_IN->gcount();YY_MyScanner_IN->clear(YY_MyScanner_IN->rdstate()&(~ios::failbit));if(YY_MyScanner_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_MyScanner_FATAL_ERROR_PURE
#define YY_MyScanner_FATAL_ERRO_NOCODE
#endif
#ifndef YY_MyScanner_FATAL_ERROR
#define YY_MyScanner_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_MyScanner_FATAL_ERROR_CODE
#ifndef YY_MyScanner_IOSTREAM
#define YY_MyScanner_FATAL_ERROR_CODE fputs( msg, YY_MyScanner_ERRFILE );putc( '\n', YY_MyScanner_ERRFILE );exit( 1 );
#else
#define YY_MyScanner_FATAL_ERROR_CODE YY_MyScanner_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_MyScanner_WRAP
#define YY_MyScanner_WRAP yy_wrap
#endif
#ifdef YY_MyScanner_WRAP_PURE
#define YY_MyScanner_WRAP_NOCODE
#endif
#ifndef YY_MyScanner_WRAP_CODE
#define YY_MyScanner_WRAP_CODE return 1;
#endif


#ifndef YY_MyScanner_INHERIT
#define YY_MyScanner_INHERIT
#endif
#ifndef YY_MyScanner_MEMBERS
#define YY_MyScanner_MEMBERS 
#endif
#ifndef YY_MyScanner_CONSTRUCTOR_PARAM
#define YY_MyScanner_CONSTRUCTOR_PARAM
#endif
#ifndef YY_MyScanner_CONSTRUCTOR_CODE
#define YY_MyScanner_CONSTRUCTOR_CODE
#endif
#ifndef YY_MyScanner_CONSTRUCTOR_INIT
#define YY_MyScanner_CONSTRUCTOR_INIT
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_MyScanner_CLASS YY_MyScanner_INHERIT
{
 private:/* data */
 YY_MyScanner_CHAR  *yy_c_buf_p;
 YY_MyScanner_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_MyScanner_CHAR  c, YY_MyScanner_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE yy_current_buffer;
 void YY_MyScanner_RESTART ( YY_MyScanner_IFILE *input_file );
 void YY_MyScanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_MyScanner_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_MyScanner_CREATE_BUFFER( YY_MyScanner_IFILE *file, int size );
 void YY_MyScanner_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_MyScanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_MyScanner_IFILE *file );
 protected: /* virtual */
 virtual void YY_MyScanner_ECHO()
#ifdef YY_MyScanner_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_MyScanner_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_MyScanner_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_MyScanner_FATAL_ERROR(char *msg)
#ifdef YY_MyScanner_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_MyScanner_WRAP()
#ifdef YY_MyScanner_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_MyScanner_CHAR  *YY_MyScanner_TEXT;
 int YY_MyScanner_LENG;
 YY_MyScanner_IFILE *YY_MyScanner_IN;
 YY_MyScanner_OFILE *YY_MyScanner_OUT;
 YY_MyScanner_LEX_RETURN YY_MyScanner_LEX ( YY_MyScanner_LEX_PARAM);
 YY_MyScanner_CLASS(YY_MyScanner_CONSTRUCTOR_PARAM) ;
#if YY_MyScanner_DEBUG != 0
 int YY_MyScanner_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_MyScanner_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 42 "MyScannerIOS.l"
#endif
#line 362 "/u/icdc/rdt/tools/lib/flexskel.h"

/* end of generated header */
